In [1]:
print("Hello, World")

Hello, World


In [5]:
import numpy as np

In [13]:
a = np.array([1,2,3])
print(a)
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

b = np.array([[1,2,3],[3,4,5]])
print(b)
print(b.shape)
print(b[0])

c = np.array([1.4,5.3,.8])
print(c)

[1 2 3]
(3,)
1 2 3
[5 2 3]
[[1 2 3]
 [3 4 5]]
(2, 3)
[1 2 3]
[1.4 5.3 0.8]


In [17]:
a = np.zeros((2,3))
print(a)

b = np.ones((1,2))
print(b)

c = np.full((2,3), 7)
print(c)

d = np.random.random((3,3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]]
[[7 7 7]
 [7 7 7]]
[[0.82207901 0.23591968 0.70112798]
 [0.43351247 0.61683932 0.57055911]
 [0.25958965 0.05275057 0.77545646]]


In [2]:
import numpy as np
a = np.array([[1,2,3,4],
             [2,3,4,5],
             [3,4,5,6]])

print(a)
print(a.shape)
b = a[:1, 1:3]
print(b)

print(a[0,1])
b[0,0,] = 75
b[0,1] = 23
print(a)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
(3, 4)
[[2 3]]
2
[[ 1 75 23  4]
 [ 2  3  4  5]
 [ 3  4  5  6]]


In [26]:
a = np.array([[1,2],
             [3,4],
             [4,5]])

print(a)
print(a>2)

print(a[a>2])

[[1 2]
 [3 4]
 [4 5]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 4 5]


In [30]:
a = np.array([[1,2],
             [3,4],
             [4,5]])
b = np.array([[1,2],
             [3,4],
             [4,5]])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(a/b)

[[ 2  4]
 [ 6  8]
 [ 8 10]]
[[0 0]
 [0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]
 [16 25]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [33]:
print(np.sum(a))

print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

19
[ 8 11]
[3 7 9]
